RegisterNUICallback('dataCheck', function(data, cb)
    print("LOG: ", json.encode(data))
    exports["gksphone"]:NuiSendMessage({event = 'app', app = data.id})
    cb('ok')
end)

RegisterNUICallback('input', function(data, cb)
    exports["gksphone"]:InputChange(data.value)
    cb('ok')
end)
